# Generated by Django 6.0.1 on 2026-02-01 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('importer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='cover_art',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
